/*select  ORDER_ID,PRODUCT_NAME from DEMO_ORDER_ITEMS
LEFT JOIN DEMO_PRODUCT_INFO
ON DEMO_ORDER_ITEMS.PRODUCT_ID = DEMO_PRODUCT_INFO.PRODUCT_ID;*/

/*SELECT ORDER_ID AS ID,ORDER_TOTAL AS TOTAL,DEMO_CUSTOMERS.CUST_FIRST_NAME AS NOMBRE
FROM DEMO_ORDERS
INNER JOIN DEMO_CUSTOMERS
ON DEMO_ORDERS.ORDER_ID = DEMO_CUSTOMERS.CUSTOMER_ID*/

--CUSTOMERS QUE NO TIENEN PEDIDOS el nombre y el estado

/*SELECT CUST_FIRST_NAME AS NOMBRE ,STATE_NAME as Estado
FROM DEMO_CUSTOMERS
LEFT JOIN DEMO_ORDERS ON DEMO_CUSTOMERS.CUSTOMER_ID = DEMO_ORDERS.CUSTOMER_ID
INNER JOIN DEMO_STATES ON DEMO_CUSTOMERS.CUST_STATE = DEMO_STATES.ST
WHERE DEMO_ORDERS.CUSTOMER_ID  IS NULL*/

--PRODUCTOS TOTALES COMPRADOS POR USUARIO
SELECT DEMO_CUSTOMERS.CUST_FIRST_NAME AS Nombre,DEMO_ORDERS.CUSTOMER_ID, Cantidad FROM
(SELECT SUM(QUANTITY) as Cantidad ,ORDER_ID FROM DEMO_ORDER_ITEMS group by ORDER_ID ORDER BY ORDER_ID)DEMO_ITEMS
INNER JOIN DEMO_ORDERS 
ON DEMO_ITEMS.ORDER_ID = DEMO_ORDERS.ORDER_ID
INNER JOIN DEMO_CUSTOMERS
ON DEMO_ORDERS.CUSTOMER_ID=DEMO_CUSTOMERS.CUSTOMER_ID
GROUP BY DEMO_CUSTOMERS.CUSTOMER_ID ,DEMO_ORDERS.CUSTOMER_ID





